name: feeling_analysis
description: Análisis de sentimientos con de comentarios de películas con OpenAI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  fluent_ui: ^4.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_icons:
  android: false
  ios: false
  image_path: "assets/images/icon.jpg"
  web:
    generate: true
    image_path: "assets/images/icon.jpg"
  windows:
    generate: true
    image_path: "assets/images/icon.jpg"
  macos:
    generate: true
    image_path: "assets/images/icon.jpg"
