name: feeling_analysis
description: Análisis de sentimientos con de comentarios de películas con OpenAI
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  dio: ^5.1.1
  equatable: ^2.0.5
  file_picker: ^5.2.10
  fluent_ui: ^4.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  hovering: ^1.0.4
  intl: ^0.17.0
  movie_api:
    path: packages/movie_api
  movie_api_remote:
    path: packages/movie_api_remote
  movie_repository:
    path: packages/movie_repository
  syncfusion_flutter_charts: ^21.1.39
  syncfusion_flutter_core: ^21.1.39

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  msix: ^3.11.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Ubuntu-Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
    - family: Ubuntu-Light
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
  assets:
    - assets/images/

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/icon.jpg"
  web:
    generate: true
    image_path: "assets/images/icon.jpg"
  windows:
    generate: true
    image_path: "assets/images/icon.jpg"
  macos:
    generate: true
    image_path: "assets/images/icon.jpg"

msix_config:
  display_name: Movie Sentiment Analyzer
  publisher_display_name: Piero Angelo Morales Alcalde
  identity_name: 29622PieroAngeloMoralesAl.MovieSentimentAnalyzer
  publisher: CN=91BE0923-E8F6-4F62-AE9E-2A123C9AC1AF
  msix_version: 1.3.0.0
  languages: es-es
  logo_path: assets/images/icon.jpg
  capabilities: internetClient
  store: true
