name: movie_api_remote
description: Movie API Remote Connection
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  movie_api:
    path: ../movie_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
